; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ProLifeServer"
#define MyAppVersion "1.0"
#define MyAppPublisher "ImagingTools GmbH"
#define MyAppURL "http://www.imagingtools.de"
#define MyAppExeName "ProLifeServer.exe"
#define BasePath GetEnv('PROLIFE_BUILD_DIR')

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf64}\ImagingTools\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputBaseFilename=ProLifeServerInstall
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Components]
Name: "server"; Description: "ProLife server"; Types: full compact custom; Flags: fixed
Name: "postgresql"; Description: "PostgreSQL 14"; Types: full

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: envPath; Description: "Add to PATH variable PostgreSQL"; Components: postgresql
    
[Files]
Source: "{#BasePath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BasePath}\*"; Excludes: "*.exe"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "postgresql.exe"; DestDir: "{app}"; Flags: deleteafterinstall; Components: postgresql


[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\postgresql.exe"; Flags: runascurrentuser; Parameters:  --mode unattended --unattendedmodeui minimal --superpassword root; Components: postgresql
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Parameters: "-t"
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Parameters: "-u"
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Parameters: "-i"

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "-t -u"

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{pf64}\PostgreSQL\14\bin"; \
    Tasks:  envPath; Check: NeedsAddPath('{pf64}\PostgreSQL\14\bin');

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
    if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
      'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
      'Path', OrigPath)
    then begin
      Result := True;
      exit;
    end;
    { look for the path with leading and trailing semicolon }
    { Pos() returns 0 if not found }
    Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

{var
  DBPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  DBPage := CreateInputQueryPage(wpSelectComponents,
    'Application SuperUser Information', '',
   'Please enter the super user information, then click Next.');
  DBPage.Add('Super user login:', False);
  DBPage.Add('Password:', False);
  DBPage.Add('Email:', False);
  
  DBPage.Values[0] := GetPreviousData('SuperuserLogin', '');
  DBPage.Values[1] := GetPreviousData('Password', '');
  DBPage.Values[2] := GetPreviousData('Email', '');
end;

procedure RegisterPreviousData(PreviousDataKey: Integer);
begin
  SetPreviousData(PreviousDataKey, 'SuperuserLogin', DBPage.Values[0]);
  SetPreviousData(PreviousDataKey, 'Password', DBPage.Values[1]); 
  SetPreviousData(PreviousDataKey, 'Email', DBPage.Values[2]); 
end;

function FileReplaceString(const FileName, SearchString, ReplaceString: string):boolean;
var
  MyFile : TStrings;
  MyText : string;
begin
  MyFile := TStringList.Create;

  try
    result := true;

    try
      MyFile.LoadFromFile(FileName);
      MyText := MyFile.Text;

      if StringChangeEx(MyText, SearchString, ReplaceString, True) > 0 then
      begin;
        MyFile.Text := MyText;
        MyFile.SaveToFile(FileName);
      end;
    except
      result := false;
    end;
  finally
    MyFile.Free;
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if CurPageID = DBPage.ID then begin
    if DBPage.Values[0] = '' then begin
      MsgBox('You must enter the login super user.', mbError, MB_OK);
      Result := False;
    end
    else if  DBPage.Values[2] = '' then
      begin
        MsgBox('You must enter the email.', mbError, MB_OK);
        Result := False;
      end
    else 
      begin
         FileReplaceString('createuser.sql', ':UserId', DBPage.Values[0]);
         FileReplaceString('createuser.sql', ':Password', DBPage.Values[1]);
         FileReplaceString('createuser.sql', ':Email', DBPage.Values[2]);
         if Exec('psql', '-h localhost -d ProLife -U postgres -p 5432 -a -q -f createuser.sql', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
         begin
          Result := True;
         end else 
           begin
            MsgBox('Database update failed:'#10#10 + SysErrorMessage(ResultCode),
            mbError, MB_OK);
            Result := False;
           end;
      end;
  end;
end;   }

