; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ProLifeServer"
#define MyAppVersion GetEnv('APP_VERSION')
#define MyAppPublisher "ImagingTools GmbH"
#define MyAppURL "http://www.imagingtools.de"
#define MyAppExeName "ProLifeServer.exe"
#define BasePath GetEnv('PROLIFE_BUILD_DIR')

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf64}\ImagingTools\ProLifeServer
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputBaseFilename=ProLifeServerInstall
Compression=lzma
SolidCompression=yes
WizardStyle=modern
CloseApplications=true

[Components]
Name: "server"; Description: "ProLife server"; Types: full compact custom; Flags: fixed
//Name: "postgresql"; Description: "PostgreSQL 14"; Types: full

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
//Name: envPath; Description: "Add to PATH variable PostgreSQL"; Components: postgresql
    
[Files]
Source: "{#BasePath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BasePath}\*"; Excludes: "*.exe,*.manifest,*.arp";  DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
//Source: "postgresql.exe"; DestDir: "{app}"; Flags: deleteafterinstall; Components: postgresql
Source: "{#BasePath}\ProLifeServerConfigurator.exe"; DestDir: "{app}"; Flags: ignoreversion
//Source: "nginx\*"; DestDir: "{app}\nginx"; Flags: recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
//Filename: "{app}\postgresql.exe"; Flags: runascurrentuser; Parameters:  --mode unattended --unattendedmodeui minimal --superpassword root; Components: postgresql
// Filename: "{app}\ProLifeServerConfigurator.exe"; Flags: runascurrentuser
//Filename: "{app}\nginx\stopNginx.bat"; Flags: runascurrentuser postinstall
//Filename: "{app}\nginx\startNginx.bat"; Flags: runascurrentuser postinstall
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent;

[UninstallRun]
//Filename: "{app}\nginx\stopNginx.bat"; Flags: runascurrentuser

//[Registry]
//Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
  //  ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{pf64}\PostgreSQL\14\bin"; \
    //Tasks:  envPath; Check: NeedsAddPath('{pf64}\PostgreSQL\14\bin');

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
    if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
      'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
      'Path', OrigPath)
    then begin
      Result := True;
      exit;
    end;
    { look for the path with leading and trailing semicolon }
    { Pos() returns 0 if not found }
    Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

function InitializeSetup(): boolean;
var
  ResultCode: integer;
begin
  if DirExists(ExpandConstant('{pf64}\ImagingTools\ProLifeServer')) then
  begin
    if Exec(ExpandConstant('{pf64}\ImagingTools\ProLifeServer\nginx\stopNginx.bat'), '', '', SW_SHOW,
       ewWaitUntilTerminated, ResultCode) then
    begin
      // Exec(ExpandConstant('{pf64}\ImagingTools\ProLifeServer\unins000.exe'), '', '', SW_SHOW,ewWaitUntilTerminated, ResultCode);
    end
    else begin
      // handle failure if necessary; ResultCode contains the error code
    end;

    // DelTree(ExpandConstant('{pf64}\ImagingTools\ProLifeServer'), True, True, True);
  end;
  // Proceed Setup
  Result := True;

end;




