TARGET = prolifesdl

include($(ACFDIR)/Config/QMake/StaticConfig.pri)
include($(IMTCOREDIR)/Config/QMake/ImtCore.pri)


# SDL
include($(IMTCOREDIR)/Config/QMake/SdlCodeGenerator.pri)

SDL_GENERATOR_SENSORS_SCHEME_PATH = $$PWD/../1.0/Sensors.sdl
SDL_CPP_SENSORS_COMPILER = $$CreateCppQmlSdlTarget(Sensors, $$SDL_GENERATOR_SENSORS_SCHEME_PATH)
$${SDL_CPP_SENSORS_COMPILER}.input = SDL_GENERATOR_SENSORS_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_SENSORS_COMPILER}

SDL_GENERATOR_LICENSES_SCHEME_PATH = $$PWD/../1.0/Licenses.sdl
SDL_CPP_LICENSES_COMPILER = $$CreateCppQmlSdlTarget(Licenses, $$SDL_GENERATOR_LICENSES_SCHEME_PATH)
$${SDL_CPP_LICENSES_COMPILER}.input = SDL_GENERATOR_LICENSES_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_LICENSES_COMPILER}

SDL_GENERATOR_ORDERS_SCHEME_PATH = $$PWD/../1.0/Orders.sdl
SDL_CPP_ORDERS_COMPILER = $$CreateCppQmlSdlTarget(Orders, $$SDL_GENERATOR_ORDERS_SCHEME_PATH)
$${SDL_CPP_ORDERS_COMPILER}.input = SDL_GENERATOR_ORDERS_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_ORDERS_COMPILER}

SDL_GENERATOR_ACCOUNTS_SCHEME_PATH = $$PWD/../1.0/Accounts.sdl
SDL_CPP_ACCOUNTS_COMPILER = $$CreateCppQmlSdlTarget(Accounts, $$SDL_GENERATOR_ACCOUNTS_SCHEME_PATH)
$${SDL_CPP_ACCOUNTS_COMPILER}.input = SDL_GENERATOR_ACCOUNTS_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_ACCOUNTS_COMPILER}

