worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
	default_type  application/octet-stream;
	client_max_body_size 1000m;

    server {
	    listen 7770;
		server_name localhost;

        location /ProLife {
		    proxy_pass http://localhost:7778;
			proxy_redirect     off;
			proxy_set_header   Host             localhost;
			proxy_set_header   X-Real-IP        localhost;
			proxy_set_header   X-Forwarded-For  localhost;
		}

        location /ProLife/wssub {
		    proxy_pass http://localhost:8778;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

        location /Lisa {
		    proxy_pass http://localhost:7776;
			proxy_redirect     off;
			proxy_set_header   Host             localhost;
			proxy_set_header   X-Real-IP        localhost;
			proxy_set_header   X-Forwarded-For  localhost;
		}

        location /Lisa/wssub {
		    proxy_pass http://localhost:8776;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

        location /Puma {
		    proxy_pass http://localhost:7778;
			proxy_redirect     off;
			proxy_set_header   Host             localhost;
			proxy_set_header   X-Real-IP        localhost;
			proxy_set_header   X-Forwarded-For  localhost;
		}

        location /Puma/wssub {
		    proxy_pass http://localhost:8778;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
	}
}
